version: '3.8'

services:

  backend:
    container_name: backend
    build: ./django_pg_job
    command: >
      bash -c "python manage.py migrate
      && python manage.py collectstatic
      && gunicorn Social_network.wsgi:application --bind 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    environment:
      - ENV=$ENV_PROD
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #    env_file:
    #      - ./.env
    environment:
      - POSTGRES_PASSWORD=1234556
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7
    restart: always
    depends_on:
      - db
    ports:
      - '5555:5555'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin@mail.ru
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5555
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin-data: